#!r6rs
(library (IntSeq Seqs Sieves sieves-cross-permutations.ss)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                                           ;;
;; sieves-cross-permutations.ss - OEIS-sequences for permutations obtained   ;;
;;                by mapping between sequences generated by various sieves   ;;
;;                                                                           ;;
;; Antti Karttunen started writing this Scheme R6RS-module Dec 04 2015 by    ;;
;; extracting the related functions from MIT/GNU-Scheme module intfun_a.scm  ;;
;; written in 2002-2015.                                                     ;;
;;                                                                           ;;
;; The OEIS-sequence data (also defs & programs) has been submitted as per   ;;
;;   http://oeis.org/wiki/The_OEIS_Contributor's_License_Agreement           ;;
;; and it is made available with                                             ;;
;;   http://oeis.org/wiki/The_OEIS_End-User_License_Agreement                ;;
;; which uses the Creative Commons Attribution Non-Commercial 3.0 license    ;;
;;   http://creativecommons.org/licenses/by-nc/3.0/                          ;;
;;                                                                           ;;
;; Thus, this module uses the same CC BY-NC 3.0 license.                     ;;
;;                                                                           ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

  (export
A255407 ;; o=1: Permutation of natural numbers: a(n) = A255127(A252460(n)).
A255408 ;; o=1: Permutation of natural numbers: a(n) = A083221(A255128(n)).

A255553 ;; o=1: Permutation of natural numbers: a(n) = A255551(A252460(n)). XFER sieve-cross-permutations.ss
A255554 ;; o=1: Permutation of natural numbers: a(n) = A083221(A255552(n)).

A260435 ;; o=1: Permutation mapping from Lucky sieve to Ludic sieve: a(1) = 1, for n > 1: a(n) = A255127(A260438(n), A260439(n)).
A260436 ;; o=1: Permutation mapping from Ludic sieve to Lucky sieve: a(1) = 1, for n > 1: a(n) = A255551(A260738(n), A260739(n)).
A260741 ;; o=1: Permutation of natural numbers: a(1) = 1, for n > 1: a(n) = A255127(A260438(n), a(A260439(n))).
A260742 ;; o=2: Permutation of natural numbers: a(1) = 1, for n > 1: a(n) = A255551(A260738(n), a(A260739(n))).
  )
  (import (rnrs base (6))
          (Intseq Memoize memoize-definec)
          (Intseq Transforms transforms-core)
          (IntSeq Seqs Triangles triangles-core)
          (IntSeq Seqs Sieves sieve-eratosthenes)
          (IntSeq Seqs Sieves sieve-lucky)
          (IntSeq Seqs Sieves sieve-ludic)
  )



(definec (A255407 n) (A255127 (A252460 n)))
(definec (A255408 n) (A083221 (A255128 n)))


(definec (A255553 n) (A255551 (A252460 n)))
(definec (A255554 n) (A083221 (A255552 n)))


(define (A260435 n) (if (<= n 1) n (A255127bi (A260438 n) (A260439 n))))

(define (A260436 n) (if (<= n 1) n (A255551bi (A260738 n) (A260739 n))))

(definec (A260741 n) (if (<= n 1) n (A255127bi (A260438 n) (A260741 (A260439 n)))))
(definec (A260742 n) (if (<= n 1) n (A255551bi (A260738 n) (A260742 (A260739 n)))))

) ;; End of module sieves-cross-permutations.ss
